name = "pizzasteve-api"
main = "index.ts"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "pizzasteve_db"
database_name = "pizzasteve-db"
database_id = "89826803-5d0f-48e4-b445-a576d287bda8"
[[kv_namespaces]]
binding = "SESSIONS"
id = "33a3bd916ab44470914268a7b012f190"

[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "dd00ace706ad4613b35a82dffc9990d4"
